(load-theme 'tango-dark t)
(setq make-backup-files nil)
(menu-bar-mode -1)
(toggle-scroll-bar -1)
(tool-bar-mode -1)
(set-face-attribute 'default nil :font "DejaVu Sans Mono 10")
(electric-indent-mode +1)
(electric-pair-mode +1)
(show-paren-mode +1)
